### ISSUE TITLE
关于模型结构

### ISSUE THREAD

**Issue by wutaiqiang** [LiyingCheng95/EntityDescriptionGeneration#2]
@LiyingCheng95 你好~，这是一篇好工作，恭喜中了EMNLP2020
我之前看过一篇类似的文章 Heterogeneous Graph Transformer for Graph-to-Sequence Learning
想问问你看过么？你觉得你的模型相比这篇论文的模型有点在哪里呢？
感谢！

**Comment by LiyingCheng95** [comment]
你好～抱歉回复的有点迟。之前没看过这篇文章。刚才简单看了下，也是个挺棒的工作。直观地来看，他们的graph也没有把原始图中的点和点直接相连，而我们的工作中Figure
4 图4和5有把原始图中的点和点直接相连，可以在一定程度上解决信息丢失的问题。这也是我们的图跟levi
graph的一个显著区别。但这两个工作用在不同任务和数据集上，具体哪个更好，可能还是需要实验来证明。

**Comment by wutaiqiang** [comment]
感谢感谢~
