### ISSUE TITLE
关于METEOR指标的参数设置

### ISSUE THREAD

**Issue by aleversn** [LiyingCheng95/EntityDescriptionGeneration#3]
你好！
感谢您的这项工作所贡献的数据集，
关于文章实验指标有个疑问就是文中似乎没有提及`METEOR`指标的参数是如何设置的？
我想在一项工作中引用您贡献的数据集，因此想了解详细的参数设置以便更直观比对。
希望能得到您的回复！

**Comment by jackwu502** [comment]
您好，关于METEOR的计算我们使用的是https://github.com/jhclark/multeval 里提供的代码。他们使用的是METEOR 1.4的版本https://github.com/jhclark/multeval#Libraries 。 我们没有对METEOR的参数进行额外的设置。您可以使用他们的代码和默认的参数对您的结果进行评估，谢谢

**Comment by minskiter** [comment]
您好！关于PARENT分数的实验指标，评估代码是否是使用https://github.com/google-research/google-research 该库的table_to_text进行评估呢？对于PARENT中的tables参数以及其余参数该如何设置呢？

**Comment by LiyingCheng95** [comment]
用的是这里的。https://github.com/google-research/language/tree/master/language/table_text_eval。
我把我当时用的相关代码传到table_text_eval文件夹下了，直接按里面readme的指令跑是可以复现论文中的结果的。参数都使用的默认参数。

**Comment by aleversn** [comment]
感谢您的解答！我们已用您提供的方法解决了问题🤝
