### ISSUE TITLE
关于模型复现结果的问题

### ISSUE THREAD

**Issue by Dicky35** [LiyingCheng95/EntityDescriptionGeneration#4]
您好，我最近在复现这篇文章的时候，按照readme中的步骤逐个执行，模型训练了100次后停止训练，但此时的bleu值十分低，为1.5e-5，解码的输出结果里面全是单词the，请问这可能是由于什么原因导致的呢？
环境：python3.6，cuda11，V100 * 1

**Comment by LiyingCheng95** [comment]
您好，应该是参数的设置原因。试一下以下这组参数？
        --batch-size 16 \
        --batch-type sentence \
        --word-min-count 3:3 \
        --num-embed 360:360 \
        --embed-dropout .5:.5 \
        --max-seq-len 149:149 \
        --encoder gcn \
        --gcn-activation relu \
        --gcn-num-hidden 360 \
        --gcn-pos-embed 360 \
        --decoder rnn \
        --num-layers and 6:2 \
        --rnn-num-hidden 360 \
        --rnn-decoder-hidden-dropout 0.2 \
        --checkpoint-frequency 1000 \
        --max-num-checkpoint-not-improved 48 \
        --initial-learning-rate 0.0003 \
        --learning-rate-reduce-factor 0.7 \
        --learning-rate-reduce-num-not-improved 8 \
        --gcn-num-layers 6 \
        --weight-init-xavier-factor-type in \
        --weight-init-scale 2.34 \
        --decode-and-evaluate 100 \
        --output sockeye/test_model \
        --overwrite-output \
        --gcn-dropout 0.1 \
        --gcn-adj-norm \
        --rnn-attention-type coverage \
        --shared-vocab \
        --weight-tying \
        --weight-tying-type src_trg_softmax \
        --attention-based-copying   \
        --weight-normalization

**Comment by Dicky35** [comment]
我尝试了这组参数，但是很快perplexity变成了NaN，然后训练程序就终止了。之后尝试吧--wright-tying-type改成了src_trg，虽然不会出现这种nan的情况，但是bleu值在169个checkpoint时还是极低。

[INFO:sockeye.training] Starting process: Decoder-2
[INFO:sockeye.training] Validation-perplexity has not improved for 1 checkpoints, best so far: 1033.447793
Model was only trained with sentences up to a length of 141, but a max_input_len of 150 is used.
[INFO:sockeye.utils] GPU 0: 10813/32510 MB (33.26%)
[INFO:sockeye.training] Epoch[0] Batch [2050]   Speed: 6.57 samples/sec 276.31 tokens/sec 0.41 updates/sec      perplexity=1428.687279
[INFO:sockeye.training] Epoch[0] Batch [2100]   Speed: 91.39 samples/sec 3436.24 tokens/sec 5.71 updates/sec    perplexity=1393.326665
[INFO:sockeye.training] Epoch[0] Batch [2150]   Speed: 93.28 samples/sec 3537.30 tokens/sec 5.83 updates/sec    perplexity=1337.257711
[INFO:sockeye.training] Epoch[0] Batch [2200]   Speed: 91.66 samples/sec 3578.30 tokens/sec 5.73 updates/sec    perplexity=1325.832591

[INFO:sockeye.training] Epoch[0] Batch [2200]   Speed: 91.66 samples/sec 3578.30 tokens/sec 5.73 updates/sec    perplexity=1325.832591
[INFO:sockeye.training] Epoch[0] Batch [2250]   Speed: 91.64 samples/sec 3606.83 tokens/sec 5.73 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2300]   Speed: 92.66 samples/sec 3543.37 tokens/sec 5.79 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2350]   Speed: 85.73 samples/sec 3443.00 tokens/sec 5.36 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2400]   Speed: 93.44 samples/sec 3558.02 tokens/sec 5.84 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2450]   Speed: 88.18 samples/sec 3752.86 tokens/sec 5.51 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2500]   Speed: 92.72 samples/sec 3530.81 tokens/sec 5.80 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2550]   Speed: 95.11 samples/sec 3423.94 tokens/sec 5.94 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2600]   Speed: 94.81 samples/sec 3489.04 tokens/sec 5.93 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2650]   Speed: 93.88 samples/sec 3559.86 tokens/sec 5.87 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2700]   Speed: 95.27 samples/sec 3460.20 tokens/sec 5.95 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2750]   Speed: 92.70 samples/sec 3589.17 tokens/sec 5.79 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2800]   Speed: 94.13 samples/sec 3524.28 tokens/sec 5.88 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2850]   Speed: 94.32 samples/sec 3455.96 tokens/sec 5.90 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2900]   Speed: 96.52 samples/sec 3428.54 tokens/sec 6.03 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [2950]   Speed: 90.82 samples/sec 3632.62 tokens/sec 5.68 updates/sec    perplexity=nan
[INFO:sockeye.training] Epoch[0] Batch [3000]   Speed: 94.31 samples/sec 3470.51 tokens/sec 5.89 updates/sec    perplexity=nan

[INFO:root] Saved params to "/home/EntityDescriptionGeneration-master/sockeye/test_model/params.00003"
[INFO:sockeye.training] Checkpoint [3]  Updates=3000 Epoch=0 Samples=48000 Time-cost=183.196 Updates/sec=5.459
[INFO:sockeye.training] Checkpoint [3]  Train-perplexity=nan
[INFO:sockeye.training] Checkpoint [3]  Validation-perplexity=nan
[INFO:sockeye.training] Decoder-2 finished: {'bleu-val': 1.0442394830388846e-06, 'chrf-val': 0.012740953901043798, 'rouge1-val': 0.0, 'rouge2-val': 0.0, 'rougel-val': 0.0, 'length-ratio-mse': 3.9346474003938505, 'avg-sec-per-sent-val': 0.2171189522743225, 'decode-walltime-val': 21.71189522743225}
[INFO:sockeye.training] Starting process: Decoder-3
[INFO:sockeye.training] Validation-perplexity has not improved for 2 checkpoints, best so far: 1033.447793
[WARNING:sockeye.training] Model optimization diverged. Last checkpoint's perplexity: nan
Model was only trained with sentences up to a length of 141, but a max_input_len of 150 is used.
[INFO:sockeye.utils] GPU 0: 10821/32510 MB (33.29%)
[WARNING:sockeye.training] Waiting for process Decoder-3 to finish.
[WARNING:sockeye.training] Had to wait 14 seconds for the Checkpoint Decoder-3 to finish. Consider increasing the checkpoint interval (updates between checkpoints, see --checkpoint-interval) or reducing the size of the validation samples that are decoded (see --decode-and-evaluate).
[INFO:sockeye.training] Decoder-3 finished: {'bleu-val': 3.926970229838963e-06, 'chrf-val': 0.043607197219204134, 'rouge1-val': 0.0005714285658775511, 'rouge2-val': 0.0, 'rougel-val': 0.000122160957445714, 'length-ratio-mse': 3.9346474003938505, 'avg-sec-per-sent-val': 0.11431475162506104, 'decode-walltime-val': 11.431475162506104}
[INFO:sockeye.training] Training finished, can be continued later. Best checkpoint: 1. Best validation perplexity: 1033.447793
[INFO:sockeye.utils] Releasing GPU 0.

**Comment by LiyingCheng95** [comment]
batch size试一下10或者14？训练的结果与batch size的关系可能比较大，之前有个同学给我说12不能收敛，改成10或14可以收敛，结果也和我论文很接近。
