### ISSUE TITLE
有关train数据集条数不匹配的问题

### ISSUE THREAD

**Issue by StevenTang1998** [LiyingCheng95/EntityDescriptionGeneration#5]
您好，我发现`sockeye/data/ENT-DESC dataset`下面的train数据集行数有点不匹配，test和dev都是对的。
这是我`wc -l *`的结果：
```
    88650 train.amr
    88649 train.amrgrh
    88652 train-entity.txt
    88649 train.grh
    88650 train_surface.pp.txt
    88652 train-triples.txt
```
请问是不是我哪里做错了？

**Comment by LiyingCheng95** [comment]
您好，以88650行的那几个文件为准。88649行的文件是少了最后一行空行。88652的文件暂时有些不匹配，但不影响模型训练，我检查一下更新后再跟您说。

**Comment by StevenTang1998** [comment]
您好，非常感谢您的回复

我对AMR了解不多，平时接触的输入形式都是三元组；我看.amr的数据感觉和-triples.txt有一些差距，好像没有边的信息？

**Comment by LiyingCheng95** [comment]
对的。

**Comment by StevenTang1998** [comment]
但是如果我需要进行kg2text任务，那么我的输入应该是三元组，但是triples文件有88652行，对应输出是88650行，我有点不知道该怎么训练？

**Comment by LiyingCheng95** [comment]
您好，我更新了输出文件train_surface.pp.txt。正确的行数均为88652行。但是train.amrgrh和train.grh文件太大无法上传，需要你自行跑一下convert_multi_graph.py，如果有问题再随时联系我！

**Comment by StevenTang1998** [comment]
非常感谢您的帮助，我应该只会用到surface.pp和triple
